
GET  http://localhost:8080/add/personnes
Accept: application/json
Authorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InlUZXVfaktnaWdaQ1Y5Uk55Q19OWCJ9.eyJpc3MiOiJodHRwczovL2JpbGFsLXByb2ppbnQtMjIyMy5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjQ4ZWRmZmMzY2VkZjlmM2FkYzdiZmY0IiwiYXVkIjpbImh0dHBzOi8vZWNvbGUvYXBpIiwiaHR0cHM6Ly9iaWxhbC1wcm9qaW50LTIyMjMuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY4NzU1MTEyNywiZXhwIjoxNjg3NjM3NTI3LCJhenAiOiIydTF4SFl6bWZSQ0hpMjhyMDEyR09PbWNXRjA0dTVwcCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MifQ.OT3io49jN4poJ4zbay1zMx2H9hF7mhIEAuW6quK_oojuCUZYhlzCchhfG_jGCk4CMEaWf7TidTyedzMs2le-QvizfuPRgVctTL57QdlMGJPS5PoobLKipM1ZiP3_-YJb7pChLUM9uOskmm0Sgv8uNyM6jRjDta3IoQ_R5GTHjfIWqX_ymFboHVOtDDrSwY5TGjFqSiYzTHGBOyxmT9E3KwxfO8qShn4hWj1CSsu379-2dRV7tIqSR9Uz_2kLfuEezMikzDo8YynmWS9IMcdqZJyKMC5JDbyn7zfADQKmAXGCfiyD75YQiy7h9Ed0byBv_vsXMyCWy1RIxPgwsQX3BA
###
GET http://localhost:8080/add/matieres
accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InlUZXVfaktnaWdaQ1Y5Uk55Q19OWCJ9.eyJpc3MiOiJodHRwczovL2JpbGFsLXByb2ppbnQtMjIyMy5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjQ4ZWRmZmMzY2VkZjlmM2FkYzdiZmY0IiwiYXVkIjpbImh0dHBzOi8vZWNvbGUvYXBpIiwiaHR0cHM6Ly9iaWxhbC1wcm9qaW50LTIyMjMuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY4NzcyMTQxMCwiZXhwIjoxNjg3ODA3ODEwLCJhenAiOiIydTF4SFl6bWZSQ0hpMjhyMDEyR09PbWNXRjA0dTVwcCIsInNjb3BlIjoib3BlbmlkIHJlYWQ6bWF0aWVyZSB3cml0ZTptYXRpZXJlIG9mZmxpbmVfYWNjZXNzIn0.hLgmVH-MXOg5p8iA458AKG_JS20y8hsaL20Bswqx3IdYgdw1lj4FHoEEM_QsavcHZF6lLy3sBN5mWylI7GDUkN82xlLRRZ-7Hil2KRP3dJ3VRoh2B7PyVBetL-uhmPLgMLhaCLIeNk9OYD8P6ll827IOpCC33DNXVUwVw6u2qE9PQkk13lqTw6pI5lLRWx1Bvg7wCJeKB4KnBiiJpd_VGmuiaAK983Kz2DD7YN-1xxTXbt_uxU8qmC6EuBL2MgR8FQ99zdgLbRt_DZbyWU2kiWbBiB7bZSiX7tXpgs3k3uYN_uPkHFxUtMhjcfqus4FhnN1tw04FPUok6R6o5xEiKQ
###
GET http://localhost:8080/add/matieres/api?page=0&size=10
accept: application/json
Authorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InlUZXVfaktnaWdaQ1Y5Uk55Q19OWCJ9.eyJpc3MiOiJodHRwczovL2JpbGFsLXByb2ppbnQtMjIyMy5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjQ4ZWRmZmMzY2VkZjlmM2FkYzdiZmY0IiwiYXVkIjpbImh0dHBzOi8vZWNvbGUvYXBpIiwiaHR0cHM6Ly9iaWxhbC1wcm9qaW50LTIyMjMuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY4NzczOTc1MywiZXhwIjoxNjg3ODI2MTUzLCJhenAiOiIydTF4SFl6bWZSQ0hpMjhyMDEyR09PbWNXRjA0dTVwcCIsInNjb3BlIjoib3BlbmlkIHJlYWQ6bWF0aWVyZSB3cml0ZTptYXRpZXJlIG9mZmxpbmVfYWNjZXNzIn0.JetJevD1l4YiPjOvr1CJVKHcZypHf49Y1PJ0obtNON5ZlqAvalSxpizgRPPa8Ykv2yC_e_sXv0xL44oxOcm0GRktiAOuqS2o7qVcSG04PmKYU7dOzG0bS144dm7wGXVYXaWU-BoejwQ8vYiE6hL59KiGSUNxuzP-W6eQP2xOMW0AAgnqJ10YgVYB_TlxgsCd7Bxh5u6-1kSEYxldUxULeVQYIj6Je8mv84QCmufLCGMTV_T-npVT55-T7xtNi-iwkfFMEgx-fTyal9ASbUAWzkBomulFul7LE6p9AQYTGKCNGlgIJRhEZaH3wRX5ThLHvK8HHr4HWVfAj-VYbROv2A