
GET  http://localhost:8080/add/personnes
Accept: application/json
Authorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InlUZXVfaktnaWdaQ1Y5Uk55Q19OWCJ9.eyJpc3MiOiJodHRwczovL2JpbGFsLXByb2ppbnQtMjIyMy5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjQ4ZWRmZmMzY2VkZjlmM2FkYzdiZmY0IiwiYXVkIjpbImh0dHBzOi8vZWNvbGUvYXBpIiwiaHR0cHM6Ly9iaWxhbC1wcm9qaW50LTIyMjMuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY4NzU1MTEyNywiZXhwIjoxNjg3NjM3NTI3LCJhenAiOiIydTF4SFl6bWZSQ0hpMjhyMDEyR09PbWNXRjA0dTVwcCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MifQ.OT3io49jN4poJ4zbay1zMx2H9hF7mhIEAuW6quK_oojuCUZYhlzCchhfG_jGCk4CMEaWf7TidTyedzMs2le-QvizfuPRgVctTL57QdlMGJPS5PoobLKipM1ZiP3_-YJb7pChLUM9uOskmm0Sgv8uNyM6jRjDta3IoQ_R5GTHjfIWqX_ymFboHVOtDDrSwY5TGjFqSiYzTHGBOyxmT9E3KwxfO8qShn4hWj1CSsu379-2dRV7tIqSR9Uz_2kLfuEezMikzDo8YynmWS9IMcdqZJyKMC5JDbyn7zfADQKmAXGCfiyD75YQiy7h9Ed0byBv_vsXMyCWy1RIxPgwsQX3BA
###
GET http://localhost:8080/add/matieres
accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InlUZXVfaktnaWdaQ1Y5Uk55Q19OWCJ9.eyJpc3MiOiJodHRwczovL2JpbGFsLXByb2ppbnQtMjIyMy5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjQ5MTA1ZWViOWE4YTgwYTQ3ZTU2OTIzIiwiYXVkIjpbImh0dHBzOi8vZWNvbGUvYXBpIiwiaHR0cHM6Ly9iaWxhbC1wcm9qaW50LTIyMjMuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY4NzYyMDE2NCwiZXhwIjoxNjg3NzA2NTY0LCJhenAiOiIydTF4SFl6bWZSQ0hpMjhyMDEyR09PbWNXRjA0dTVwcCIsInNjb3BlIjoib3BlbmlkIHJlYWQ6YWxsLW1hdGllcmUgb2ZmbGluZV9hY2Nlc3MifQ.ghm-QZWD_CatinlKEkBp9zOuQ5LcpsX-pszJmJJGxb_dbnunB8-TVp7HOVugcgRawteyD6nhZoW6u6NRtxdvKQJH7YpppK87SNdmS2W7YLKAG7TODszBnsvhB6qTG9qFfYVWHD4wzugdbddoq8XgTLYG7M4Q9R-q4KaMLhSvoRtMdEIn5xcq7jcNgwD0Z7s1H3vMj_GTQ87U-sKCUxjKiPnloflD88Dc-7fCUwoU_Qz7k3m5qZzwaSqE0JTlWrIeHbxni1cBFObSaP3-3kyTFpkVdgG28fPibF0My1n0lAYjLrUR9hvi4s1oNjWU5YgPNTMib7psARPFYMQHMH664A
###
GET http://localhost:8080/add/matieres/{etudiantId}
accept: application/json