image: maven:3.8.1-openjdk-17

pipelines:
  default:
    - step:
        name: Build
        script:
          - cd ecole
          - mvn install -DskipTests
    - step:
        name: Test
        script:
          - cd ecole
          - mvn test
